/* automatically generated by rust-bindgen 0.72.1 */

// @generated by bindgen from vendor/moonlight-common-c/src/Limelight.h.
// Regenerate: bindgen vendor/moonlight-common-c/src/Limelight.h -o crates/tempest-core/src/moonlight/sys.rs \
//   --allowlist-file ".*Limelight\.h" --no-layout-tests -- -I vendor/moonlight-common-c/src

pub const STREAM_CFG_LOCAL: u32 = 0;
pub const STREAM_CFG_REMOTE: u32 = 1;
pub const STREAM_CFG_AUTO: u32 = 2;
pub const COLORSPACE_REC_601: u32 = 0;
pub const COLORSPACE_REC_709: u32 = 1;
pub const COLORSPACE_REC_2020: u32 = 2;
pub const COLOR_RANGE_LIMITED: u32 = 0;
pub const COLOR_RANGE_FULL: u32 = 1;
pub const ENCFLG_NONE: u32 = 0;
pub const ENCFLG_AUDIO: u32 = 1;
pub const ENCFLG_VIDEO: u32 = 2;
pub const ENCFLG_ALL: u32 = 4294967295;
pub const BUFFER_TYPE_PICDATA: u32 = 0;
pub const BUFFER_TYPE_SPS: u32 = 1;
pub const BUFFER_TYPE_PPS: u32 = 2;
pub const BUFFER_TYPE_VPS: u32 = 3;
pub const FRAME_TYPE_PFRAME: u32 = 0;
pub const FRAME_TYPE_IDR: u32 = 1;
pub const AUDIO_CONFIGURATION_MAX_CHANNEL_COUNT: u32 = 8;
pub const VIDEO_FORMAT_H264: u32 = 1;
pub const VIDEO_FORMAT_H264_HIGH8_444: u32 = 4;
pub const VIDEO_FORMAT_H265: u32 = 256;
pub const VIDEO_FORMAT_H265_MAIN10: u32 = 512;
pub const VIDEO_FORMAT_H265_REXT8_444: u32 = 1024;
pub const VIDEO_FORMAT_H265_REXT10_444: u32 = 2048;
pub const VIDEO_FORMAT_AV1_MAIN8: u32 = 4096;
pub const VIDEO_FORMAT_AV1_MAIN10: u32 = 8192;
pub const VIDEO_FORMAT_AV1_HIGH8_444: u32 = 16384;
pub const VIDEO_FORMAT_AV1_HIGH10_444: u32 = 32768;
pub const VIDEO_FORMAT_MASK_H264: u32 = 15;
pub const VIDEO_FORMAT_MASK_H265: u32 = 3840;
pub const VIDEO_FORMAT_MASK_AV1: u32 = 61440;
pub const VIDEO_FORMAT_MASK_10BIT: u32 = 43520;
pub const VIDEO_FORMAT_MASK_YUV444: u32 = 52228;
pub const CAPABILITY_DIRECT_SUBMIT: u32 = 1;
pub const CAPABILITY_REFERENCE_FRAME_INVALIDATION_AVC: u32 = 2;
pub const CAPABILITY_REFERENCE_FRAME_INVALIDATION_HEVC: u32 = 4;
pub const CAPABILITY_SLOW_OPUS_DECODER: u32 = 8;
pub const CAPABILITY_SUPPORTS_ARBITRARY_AUDIO_DURATION: u32 = 16;
pub const CAPABILITY_PULL_RENDERER: u32 = 32;
pub const CAPABILITY_REFERENCE_FRAME_INVALIDATION_AV1: u32 = 64;
pub const DR_OK: u32 = 0;
pub const DR_NEED_IDR: i32 = -1;
pub const STAGE_NONE: u32 = 0;
pub const STAGE_PLATFORM_INIT: u32 = 1;
pub const STAGE_NAME_RESOLUTION: u32 = 2;
pub const STAGE_AUDIO_STREAM_INIT: u32 = 3;
pub const STAGE_RTSP_HANDSHAKE: u32 = 4;
pub const STAGE_CONTROL_STREAM_INIT: u32 = 5;
pub const STAGE_VIDEO_STREAM_INIT: u32 = 6;
pub const STAGE_INPUT_STREAM_INIT: u32 = 7;
pub const STAGE_CONTROL_STREAM_START: u32 = 8;
pub const STAGE_VIDEO_STREAM_START: u32 = 9;
pub const STAGE_AUDIO_STREAM_START: u32 = 10;
pub const STAGE_INPUT_STREAM_START: u32 = 11;
pub const STAGE_MAX: u32 = 12;
pub const ML_ERROR_GRACEFUL_TERMINATION: u32 = 0;
pub const ML_ERROR_NO_VIDEO_TRAFFIC: i32 = -100;
pub const ML_ERROR_NO_VIDEO_FRAME: i32 = -101;
pub const ML_ERROR_UNEXPECTED_EARLY_TERMINATION: i32 = -102;
pub const ML_ERROR_PROTECTED_CONTENT: i32 = -103;
pub const ML_ERROR_FRAME_CONVERSION: i32 = -104;
pub const CONN_STATUS_OKAY: u32 = 0;
pub const CONN_STATUS_POOR: u32 = 1;
pub const DS_EFFECT_PAYLOAD_SIZE: u32 = 10;
pub const DS_EFFECT_RIGHT_TRIGGER: u32 = 4;
pub const DS_EFFECT_LEFT_TRIGGER: u32 = 8;
pub const SCM_H264: u32 = 1;
pub const SCM_HEVC: u32 = 256;
pub const SCM_HEVC_MAIN10: u32 = 512;
pub const SCM_AV1_MAIN8: u32 = 65536;
pub const SCM_AV1_MAIN10: u32 = 131072;
pub const SCM_H264_HIGH8_444: u32 = 262144;
pub const SCM_HEVC_REXT8_444: u32 = 524288;
pub const SCM_HEVC_REXT10_444: u32 = 1048576;
pub const SCM_AV1_HIGH8_444: u32 = 2097152;
pub const SCM_AV1_HIGH10_444: u32 = 4194304;
pub const SCM_MASK_H264: u32 = 262145;
pub const SCM_MASK_HEVC: u32 = 1573632;
pub const SCM_MASK_AV1: u32 = 6488064;
pub const SCM_MASK_10BIT: u32 = 5374464;
pub const SCM_MASK_YUV444: u32 = 8126464;
pub const LI_ERR_UNSUPPORTED: i32 = -5501;
pub const LI_TOUCH_EVENT_HOVER: u32 = 0;
pub const LI_TOUCH_EVENT_DOWN: u32 = 1;
pub const LI_TOUCH_EVENT_UP: u32 = 2;
pub const LI_TOUCH_EVENT_MOVE: u32 = 3;
pub const LI_TOUCH_EVENT_CANCEL: u32 = 4;
pub const LI_TOUCH_EVENT_BUTTON_ONLY: u32 = 5;
pub const LI_TOUCH_EVENT_HOVER_LEAVE: u32 = 6;
pub const LI_TOUCH_EVENT_CANCEL_ALL: u32 = 7;
pub const LI_ROT_UNKNOWN: u32 = 65535;
pub const LI_TOOL_TYPE_UNKNOWN: u32 = 0;
pub const LI_TOOL_TYPE_PEN: u32 = 1;
pub const LI_TOOL_TYPE_ERASER: u32 = 2;
pub const LI_PEN_BUTTON_PRIMARY: u32 = 1;
pub const LI_PEN_BUTTON_SECONDARY: u32 = 2;
pub const LI_PEN_BUTTON_TERTIARY: u32 = 4;
pub const LI_TILT_UNKNOWN: u32 = 255;
pub const BUTTON_ACTION_PRESS: u32 = 7;
pub const BUTTON_ACTION_RELEASE: u32 = 8;
pub const BUTTON_LEFT: u32 = 1;
pub const BUTTON_MIDDLE: u32 = 2;
pub const BUTTON_RIGHT: u32 = 3;
pub const BUTTON_X1: u32 = 4;
pub const BUTTON_X2: u32 = 5;
pub const KEY_ACTION_DOWN: u32 = 3;
pub const KEY_ACTION_UP: u32 = 4;
pub const MODIFIER_SHIFT: u32 = 1;
pub const MODIFIER_CTRL: u32 = 2;
pub const MODIFIER_ALT: u32 = 4;
pub const MODIFIER_META: u32 = 8;
pub const SS_KBE_FLAG_NON_NORMALIZED: u32 = 1;
pub const A_FLAG: u32 = 4096;
pub const B_FLAG: u32 = 8192;
pub const X_FLAG: u32 = 16384;
pub const Y_FLAG: u32 = 32768;
pub const UP_FLAG: u32 = 1;
pub const DOWN_FLAG: u32 = 2;
pub const LEFT_FLAG: u32 = 4;
pub const RIGHT_FLAG: u32 = 8;
pub const LB_FLAG: u32 = 256;
pub const RB_FLAG: u32 = 512;
pub const PLAY_FLAG: u32 = 16;
pub const BACK_FLAG: u32 = 32;
pub const LS_CLK_FLAG: u32 = 64;
pub const RS_CLK_FLAG: u32 = 128;
pub const SPECIAL_FLAG: u32 = 1024;
pub const PADDLE1_FLAG: u32 = 65536;
pub const PADDLE2_FLAG: u32 = 131072;
pub const PADDLE3_FLAG: u32 = 262144;
pub const PADDLE4_FLAG: u32 = 524288;
pub const TOUCHPAD_FLAG: u32 = 1048576;
pub const MISC_FLAG: u32 = 2097152;
pub const LI_CTYPE_UNKNOWN: u32 = 0;
pub const LI_CTYPE_XBOX: u32 = 1;
pub const LI_CTYPE_PS: u32 = 2;
pub const LI_CTYPE_NINTENDO: u32 = 3;
pub const LI_CCAP_ANALOG_TRIGGERS: u32 = 1;
pub const LI_CCAP_RUMBLE: u32 = 2;
pub const LI_CCAP_TRIGGER_RUMBLE: u32 = 4;
pub const LI_CCAP_TOUCHPAD: u32 = 8;
pub const LI_CCAP_ACCEL: u32 = 16;
pub const LI_CCAP_GYRO: u32 = 32;
pub const LI_CCAP_BATTERY_STATE: u32 = 64;
pub const LI_CCAP_RGB_LED: u32 = 128;
pub const LI_CCAP_DUAL_TOUCHPAD: u32 = 256;
pub const LI_MOTION_TYPE_ACCEL: u32 = 1;
pub const LI_MOTION_TYPE_GYRO: u32 = 2;
pub const LI_BATTERY_STATE_UNKNOWN: u32 = 0;
pub const LI_BATTERY_STATE_NOT_PRESENT: u32 = 1;
pub const LI_BATTERY_STATE_DISCHARGING: u32 = 2;
pub const LI_BATTERY_STATE_CHARGING: u32 = 3;
pub const LI_BATTERY_STATE_NOT_CHARGING: u32 = 4;
pub const LI_BATTERY_STATE_FULL: u32 = 5;
pub const LI_BATTERY_PERCENTAGE_UNKNOWN: u32 = 255;
pub const ML_PORT_INDEX_TCP_47984: u32 = 0;
pub const ML_PORT_INDEX_TCP_47989: u32 = 1;
pub const ML_PORT_INDEX_TCP_48010: u32 = 2;
pub const ML_PORT_INDEX_UDP_47998: u32 = 8;
pub const ML_PORT_INDEX_UDP_47999: u32 = 9;
pub const ML_PORT_INDEX_UDP_48000: u32 = 10;
pub const ML_PORT_INDEX_UDP_48010: u32 = 11;
pub const ML_PORT_FLAG_ALL: u32 = 4294967295;
pub const ML_PORT_FLAG_TCP_47984: u32 = 1;
pub const ML_PORT_FLAG_TCP_47989: u32 = 2;
pub const ML_PORT_FLAG_TCP_48010: u32 = 4;
pub const ML_PORT_FLAG_UDP_47998: u32 = 256;
pub const ML_PORT_FLAG_UDP_47999: u32 = 512;
pub const ML_PORT_FLAG_UDP_48000: u32 = 1024;
pub const ML_PORT_FLAG_UDP_48010: u32 = 2048;
pub const ML_TEST_RESULT_INCONCLUSIVE: u32 = 4294967295;
pub const LI_FF_PEN_TOUCH_EVENTS: u32 = 1;
pub const LI_FF_CONTROLLER_TOUCH_EVENTS: u32 = 2;
unsafe extern "C" {
    pub fn LiGetLaunchUrlQueryParameters() -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _STREAM_CONFIGURATION {
    pub width: ::std::os::raw::c_int,
    pub height: ::std::os::raw::c_int,
    pub fps: ::std::os::raw::c_int,
    pub bitrate: ::std::os::raw::c_int,
    pub packetSize: ::std::os::raw::c_int,
    pub streamingRemotely: ::std::os::raw::c_int,
    pub audioConfiguration: ::std::os::raw::c_int,
    pub supportedVideoFormats: ::std::os::raw::c_int,
    pub clientRefreshRateX100: ::std::os::raw::c_int,
    pub colorSpace: ::std::os::raw::c_int,
    pub colorRange: ::std::os::raw::c_int,
    pub encryptionFlags: ::std::os::raw::c_int,
    pub remoteInputAesKey: [::std::os::raw::c_char; 16usize],
    pub remoteInputAesIv: [::std::os::raw::c_char; 16usize],
}
pub type STREAM_CONFIGURATION = _STREAM_CONFIGURATION;
pub type PSTREAM_CONFIGURATION = *mut _STREAM_CONFIGURATION;
unsafe extern "C" {
    pub fn LiInitializeStreamConfiguration(streamConfig: PSTREAM_CONFIGURATION);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _LENTRY {
    pub next: *mut _LENTRY,
    pub data: *mut ::std::os::raw::c_char,
    pub length: ::std::os::raw::c_int,
    pub bufferType: ::std::os::raw::c_int,
}
pub type LENTRY = _LENTRY;
pub type PLENTRY = *mut _LENTRY;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _DECODE_UNIT {
    pub frameNumber: ::std::os::raw::c_int,
    pub frameType: ::std::os::raw::c_int,
    pub frameHostProcessingLatency: u16,
    pub receiveTimeUs: u64,
    pub enqueueTimeUs: u64,
    pub presentationTimeUs: u64,
    pub rtpTimestamp: u32,
    pub fullLength: ::std::os::raw::c_int,
    pub bufferList: PLENTRY,
    pub hdrActive: bool,
    pub colorspace: u8,
}
pub type DECODE_UNIT = _DECODE_UNIT;
pub type PDECODE_UNIT = *mut _DECODE_UNIT;
pub type DecoderRendererSetup = ::std::option::Option<
    unsafe extern "C" fn(
        videoFormat: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        redrawRate: ::std::os::raw::c_int,
        context: *mut ::std::os::raw::c_void,
        drFlags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
pub type DecoderRendererStart = ::std::option::Option<unsafe extern "C" fn()>;
pub type DecoderRendererStop = ::std::option::Option<unsafe extern "C" fn()>;
pub type DecoderRendererCleanup = ::std::option::Option<unsafe extern "C" fn()>;
pub type DecoderRendererSubmitDecodeUnit =
    ::std::option::Option<unsafe extern "C" fn(decodeUnit: PDECODE_UNIT) -> ::std::os::raw::c_int>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _DECODER_RENDERER_CALLBACKS {
    pub setup: DecoderRendererSetup,
    pub start: DecoderRendererStart,
    pub stop: DecoderRendererStop,
    pub cleanup: DecoderRendererCleanup,
    pub submitDecodeUnit: DecoderRendererSubmitDecodeUnit,
    pub capabilities: ::std::os::raw::c_int,
}
pub type DECODER_RENDERER_CALLBACKS = _DECODER_RENDERER_CALLBACKS;
pub type PDECODER_RENDERER_CALLBACKS = *mut _DECODER_RENDERER_CALLBACKS;
unsafe extern "C" {
    pub fn LiInitializeVideoCallbacks(drCallbacks: PDECODER_RENDERER_CALLBACKS);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _OPUS_MULTISTREAM_CONFIGURATION {
    pub sampleRate: ::std::os::raw::c_int,
    pub channelCount: ::std::os::raw::c_int,
    pub streams: ::std::os::raw::c_int,
    pub coupledStreams: ::std::os::raw::c_int,
    pub samplesPerFrame: ::std::os::raw::c_int,
    pub mapping: [::std::os::raw::c_uchar; 8usize],
}
pub type OPUS_MULTISTREAM_CONFIGURATION = _OPUS_MULTISTREAM_CONFIGURATION;
pub type POPUS_MULTISTREAM_CONFIGURATION = *mut _OPUS_MULTISTREAM_CONFIGURATION;
pub type AudioRendererInit = ::std::option::Option<
    unsafe extern "C" fn(
        audioConfiguration: ::std::os::raw::c_int,
        opusConfig: POPUS_MULTISTREAM_CONFIGURATION,
        context: *mut ::std::os::raw::c_void,
        arFlags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
pub type AudioRendererStart = ::std::option::Option<unsafe extern "C" fn()>;
pub type AudioRendererStop = ::std::option::Option<unsafe extern "C" fn()>;
pub type AudioRendererCleanup = ::std::option::Option<unsafe extern "C" fn()>;
pub type AudioRendererDecodeAndPlaySample = ::std::option::Option<
    unsafe extern "C" fn(
        sampleData: *mut ::std::os::raw::c_char,
        sampleLength: ::std::os::raw::c_int,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _AUDIO_RENDERER_CALLBACKS {
    pub init: AudioRendererInit,
    pub start: AudioRendererStart,
    pub stop: AudioRendererStop,
    pub cleanup: AudioRendererCleanup,
    pub decodeAndPlaySample: AudioRendererDecodeAndPlaySample,
    pub capabilities: ::std::os::raw::c_int,
}
pub type AUDIO_RENDERER_CALLBACKS = _AUDIO_RENDERER_CALLBACKS;
pub type PAUDIO_RENDERER_CALLBACKS = *mut _AUDIO_RENDERER_CALLBACKS;
unsafe extern "C" {
    pub fn LiInitializeAudioCallbacks(arCallbacks: PAUDIO_RENDERER_CALLBACKS);
}
pub type ConnListenerStageStarting =
    ::std::option::Option<unsafe extern "C" fn(stage: ::std::os::raw::c_int)>;
pub type ConnListenerStageComplete =
    ::std::option::Option<unsafe extern "C" fn(stage: ::std::os::raw::c_int)>;
pub type ConnListenerStageFailed = ::std::option::Option<
    unsafe extern "C" fn(stage: ::std::os::raw::c_int, errorCode: ::std::os::raw::c_int),
>;
pub type ConnListenerConnectionStarted = ::std::option::Option<unsafe extern "C" fn()>;
pub type ConnListenerConnectionTerminated =
    ::std::option::Option<unsafe extern "C" fn(errorCode: ::std::os::raw::c_int)>;
pub type ConnListenerLogMessage =
    ::std::option::Option<unsafe extern "C" fn(format: *const ::std::os::raw::c_char, ...)>;
pub type ConnListenerRumble = ::std::option::Option<
    unsafe extern "C" fn(
        controllerNumber: ::std::os::raw::c_ushort,
        lowFreqMotor: ::std::os::raw::c_ushort,
        highFreqMotor: ::std::os::raw::c_ushort,
    ),
>;
pub type ConnListenerConnectionStatusUpdate =
    ::std::option::Option<unsafe extern "C" fn(connectionStatus: ::std::os::raw::c_int)>;
pub type ConnListenerSetHdrMode = ::std::option::Option<unsafe extern "C" fn(hdrEnabled: bool)>;
pub type ConnListenerRumbleTriggers = ::std::option::Option<
    unsafe extern "C" fn(controllerNumber: u16, leftTriggerMotor: u16, rightTriggerMotor: u16),
>;
pub type ConnListenerSetMotionEventState = ::std::option::Option<
    unsafe extern "C" fn(controllerNumber: u16, motionType: u8, reportRateHz: u16),
>;
pub type ConnListenerSetAdaptiveTriggers = ::std::option::Option<
    unsafe extern "C" fn(
        controllerNumber: u16,
        eventFlags: u8,
        typeLeft: u8,
        typeRight: u8,
        left: *mut u8,
        right: *mut u8,
    ),
>;
pub type ConnListenerSetControllerLED =
    ::std::option::Option<unsafe extern "C" fn(controllerNumber: u16, r: u8, g: u8, b: u8)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _CONNECTION_LISTENER_CALLBACKS {
    pub stageStarting: ConnListenerStageStarting,
    pub stageComplete: ConnListenerStageComplete,
    pub stageFailed: ConnListenerStageFailed,
    pub connectionStarted: ConnListenerConnectionStarted,
    pub connectionTerminated: ConnListenerConnectionTerminated,
    pub logMessage: ConnListenerLogMessage,
    pub rumble: ConnListenerRumble,
    pub connectionStatusUpdate: ConnListenerConnectionStatusUpdate,
    pub setHdrMode: ConnListenerSetHdrMode,
    pub rumbleTriggers: ConnListenerRumbleTriggers,
    pub setMotionEventState: ConnListenerSetMotionEventState,
    pub setControllerLED: ConnListenerSetControllerLED,
    pub setAdaptiveTriggers: ConnListenerSetAdaptiveTriggers,
}
pub type CONNECTION_LISTENER_CALLBACKS = _CONNECTION_LISTENER_CALLBACKS;
pub type PCONNECTION_LISTENER_CALLBACKS = *mut _CONNECTION_LISTENER_CALLBACKS;
unsafe extern "C" {
    pub fn LiInitializeConnectionCallbacks(clCallbacks: PCONNECTION_LISTENER_CALLBACKS);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _SERVER_INFORMATION {
    pub address: *const ::std::os::raw::c_char,
    pub serverInfoAppVersion: *const ::std::os::raw::c_char,
    pub serverInfoGfeVersion: *const ::std::os::raw::c_char,
    pub rtspSessionUrl: *const ::std::os::raw::c_char,
    pub serverCodecModeSupport: ::std::os::raw::c_int,
}
pub type SERVER_INFORMATION = _SERVER_INFORMATION;
pub type PSERVER_INFORMATION = *mut _SERVER_INFORMATION;
unsafe extern "C" {
    pub fn LiInitializeServerInformation(serverInfo: PSERVER_INFORMATION);
}
unsafe extern "C" {
    pub fn LiStartConnection(
        serverInfo: PSERVER_INFORMATION,
        streamConfig: PSTREAM_CONFIGURATION,
        clCallbacks: PCONNECTION_LISTENER_CALLBACKS,
        drCallbacks: PDECODER_RENDERER_CALLBACKS,
        arCallbacks: PAUDIO_RENDERER_CALLBACKS,
        renderContext: *mut ::std::os::raw::c_void,
        drFlags: ::std::os::raw::c_int,
        audioContext: *mut ::std::os::raw::c_void,
        arFlags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiStopConnection();
}
unsafe extern "C" {
    pub fn LiInterruptConnection();
}
unsafe extern "C" {
    pub fn LiGetStageName(stage: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn LiGetEstimatedRttInfo(estimatedRtt: *mut u32, estimatedRttVariance: *mut u32) -> bool;
}
unsafe extern "C" {
    pub fn LiSendMouseMoveEvent(
        deltaX: ::std::os::raw::c_short,
        deltaY: ::std::os::raw::c_short,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendMousePositionEvent(
        x: ::std::os::raw::c_short,
        y: ::std::os::raw::c_short,
        referenceWidth: ::std::os::raw::c_short,
        referenceHeight: ::std::os::raw::c_short,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendMouseMoveAsMousePositionEvent(
        deltaX: ::std::os::raw::c_short,
        deltaY: ::std::os::raw::c_short,
        referenceWidth: ::std::os::raw::c_short,
        referenceHeight: ::std::os::raw::c_short,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendTouchEvent(
        eventType: u8,
        pointerId: u32,
        x: f32,
        y: f32,
        pressureOrDistance: f32,
        contactAreaMajor: f32,
        contactAreaMinor: f32,
        rotation: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendPenEvent(
        eventType: u8,
        toolType: u8,
        penButtons: u8,
        x: f32,
        y: f32,
        pressureOrDistance: f32,
        contactAreaMajor: f32,
        contactAreaMinor: f32,
        rotation: u16,
        tilt: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendMouseButtonEvent(
        action: ::std::os::raw::c_char,
        button: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendKeyboardEvent(
        keyCode: ::std::os::raw::c_short,
        keyAction: ::std::os::raw::c_char,
        modifiers: ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendKeyboardEvent2(
        keyCode: ::std::os::raw::c_short,
        keyAction: ::std::os::raw::c_char,
        modifiers: ::std::os::raw::c_char,
        flags: ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendUtf8TextEvent(
        text: *const ::std::os::raw::c_char,
        length: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendControllerEvent(
        buttonFlags: ::std::os::raw::c_int,
        leftTrigger: ::std::os::raw::c_uchar,
        rightTrigger: ::std::os::raw::c_uchar,
        leftStickX: ::std::os::raw::c_short,
        leftStickY: ::std::os::raw::c_short,
        rightStickX: ::std::os::raw::c_short,
        rightStickY: ::std::os::raw::c_short,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendMultiControllerEvent(
        controllerNumber: ::std::os::raw::c_short,
        activeGamepadMask: ::std::os::raw::c_short,
        buttonFlags: ::std::os::raw::c_int,
        leftTrigger: ::std::os::raw::c_uchar,
        rightTrigger: ::std::os::raw::c_uchar,
        leftStickX: ::std::os::raw::c_short,
        leftStickY: ::std::os::raw::c_short,
        rightStickX: ::std::os::raw::c_short,
        rightStickY: ::std::os::raw::c_short,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendControllerArrivalEvent(
        controllerNumber: u8,
        activeGamepadMask: u16,
        type_: u8,
        supportedButtonFlags: u32,
        capabilities: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendControllerTouchEvent(
        controllerNumber: u8,
        eventType: u8,
        pointerId: u32,
        x: f32,
        y: f32,
        pressure: f32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendControllerTouchEvent2(
        controllerNumber: u8,
        eventType: u8,
        touchpadIndex: u8,
        pointerId: u32,
        x: f32,
        y: f32,
        pressure: f32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendControllerMotionEvent(
        controllerNumber: u8,
        motionType: u8,
        x: f32,
        y: f32,
        z: f32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendControllerBatteryEvent(
        controllerNumber: u8,
        batteryState: u8,
        batteryPercentage: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendScrollEvent(scrollClicks: ::std::os::raw::c_schar) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendHighResScrollEvent(scrollAmount: ::std::os::raw::c_short)
        -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendHScrollEvent(scrollClicks: ::std::os::raw::c_schar) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiSendHighResHScrollEvent(
        scrollAmount: ::std::os::raw::c_short,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiGetMicroseconds() -> u64;
}
unsafe extern "C" {
    pub fn LiGetMillis() -> u64;
}
unsafe extern "C" {
    pub fn LiFindExternalAddressIP4(
        stunServer: *const ::std::os::raw::c_char,
        stunPort: ::std::os::raw::c_ushort,
        wanAddr: *mut ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiGetPendingVideoFrames() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiGetPendingAudioFrames() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiGetPendingAudioDuration() -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _RTP_AUDIO_STATS {
    pub packetCountAudio: u32,
    pub packetCountFec: u32,
    pub packetCountFecRecovered: u32,
    pub packetCountFecFailed: u32,
    pub packetCountOOS: u32,
    pub packetCountInvalid: u32,
    pub packetCountFecInvalid: u32,
}
pub type RTP_AUDIO_STATS = _RTP_AUDIO_STATS;
pub type PRTP_AUDIO_STATS = *mut _RTP_AUDIO_STATS;
unsafe extern "C" {
    pub fn LiGetRTPAudioStats() -> *const RTP_AUDIO_STATS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _RTP_VIDEO_STATS {
    pub packetCountVideo: u32,
    pub packetCountFec: u32,
    pub packetCountFecRecovered: u32,
    pub packetCountFecFailed: u32,
    pub packetCountOOS: u32,
    pub packetCountInvalid: u32,
    pub packetCountFecInvalid: u32,
}
pub type RTP_VIDEO_STATS = _RTP_VIDEO_STATS;
pub type PRTP_VIDEO_STATS = *mut _RTP_VIDEO_STATS;
unsafe extern "C" {
    pub fn LiGetRTPVideoStats() -> *const RTP_VIDEO_STATS;
}
unsafe extern "C" {
    pub fn LiGetPortFlagsFromStage(stage: ::std::os::raw::c_int) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn LiGetPortFlagsFromTerminationErrorCode(
        errorCode: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn LiGetProtocolFromPortFlagIndex(
        portFlagIndex: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LiGetPortFromPortFlagIndex(
        portFlagIndex: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_ushort;
}
unsafe extern "C" {
    pub fn LiStringifyPortFlags(
        portFlags: ::std::os::raw::c_uint,
        separator: *const ::std::os::raw::c_char,
        outputBuffer: *mut ::std::os::raw::c_char,
        outputBufferLength: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn LiTestClientConnectivity(
        testServer: *const ::std::os::raw::c_char,
        referencePort: ::std::os::raw::c_ushort,
        testPortFlags: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_uint;
}
pub type VIDEO_FRAME_HANDLE = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    pub fn LiWaitForNextVideoFrame(
        frameHandle: *mut VIDEO_FRAME_HANDLE,
        decodeUnit: *mut PDECODE_UNIT,
    ) -> bool;
}
unsafe extern "C" {
    pub fn LiPollNextVideoFrame(
        frameHandle: *mut VIDEO_FRAME_HANDLE,
        decodeUnit: *mut PDECODE_UNIT,
    ) -> bool;
}
unsafe extern "C" {
    pub fn LiPeekNextVideoFrame(decodeUnit: *mut PDECODE_UNIT) -> bool;
}
unsafe extern "C" {
    pub fn LiWakeWaitForVideoFrame();
}
unsafe extern "C" {
    pub fn LiCompleteVideoFrame(handle: VIDEO_FRAME_HANDLE, drStatus: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn LiGetCurrentHostDisplayHdrMode() -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _SS_HDR_METADATA {
    pub displayPrimaries: [_SS_HDR_METADATA__bindgen_ty_1; 3usize],
    pub whitePoint: _SS_HDR_METADATA__bindgen_ty_2,
    pub maxDisplayLuminance: u16,
    pub minDisplayLuminance: u16,
    pub maxContentLightLevel: u16,
    pub maxFrameAverageLightLevel: u16,
    pub maxFullFrameLuminance: u16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _SS_HDR_METADATA__bindgen_ty_1 {
    pub x: u16,
    pub y: u16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _SS_HDR_METADATA__bindgen_ty_2 {
    pub x: u16,
    pub y: u16,
}
pub type SS_HDR_METADATA = _SS_HDR_METADATA;
pub type PSS_HDR_METADATA = *mut _SS_HDR_METADATA;
unsafe extern "C" {
    pub fn LiGetHdrMetadata(metadata: PSS_HDR_METADATA) -> bool;
}
unsafe extern "C" {
    pub fn LiRequestIdrFrame();
}
unsafe extern "C" {
    pub fn LiGetHostFeatureFlags() -> u32;
}
